#!/bin/sh
# Create a link to this file at .git/hooks/pre-commit to
# force PEP8 validation prior to committing
#
# Ignored violations:
#
#   W504: Line break after binary operator
#   E501: Line too long

exec 1>&2

EXIT=0
RED='\033[0;31m'
YELLOW='\033[0;33m'
NOCOLOR='\033[0m'
STATIC_DIR="$PWD/netbox/project-static"

if [ -d ./venv/ ]; then
    VENV="$PWD/venv"
    if [ -e $VENV/bin/python ]; then
        PATH=$VENV/bin:$PATH
    elif [ -e $VENV/Scripts/python.exe ]; then
        PATH=$VENV/Scripts:$PATH
    fi
fi

if [ ${NOVALIDATE} ]; then
  echo "${YELLOW}Skipping validation checks${NOCOLOR}"
  exit $EXIT
fi

echo "Validating PEP8 compliance..."
pycodestyle --ignore=W504,E501 --exclude=node_modules netbox/
if [ $? != 0 ]; then
	EXIT=1
fi

echo "Checking for missing migrations..."
python netbox/manage.py makemigrations --dry-run --check
if [ $? != 0 ]; then
	EXIT=1
fi

echo "Checking UI ESLint, TypeScript, and Prettier compliance..."
UI_VALIDATION_OUTPUT="$(yarn --cwd "$STATIC_DIR" validate 2>&1)"
if [ $? != 0 ]; then
  printf "$UI_VALIDATION_OUTPUT\n"
	EXIT=1
fi

echo "Running UI tests..."
JEST_OUTPUT="$(yarn --cwd "$STATIC_DIR" test 2>&1)"
if [ $? != 0 ]; then
  printf "$JEST_OUTPUT\n"
	EXIT=1
fi

if [ $EXIT != 0 ]; then
  printf "${RED}COMMIT FAILED${NOCOLOR}\n"
fi

exit $EXIT
